<?php
/**
 * @var \Inchoo\TicketManager\Block\TicketReply\ListBlock $block
 */
$ticket = $block->getTicket();
$ticketReplyList = $block->getTicketReplies()->getItems();
if ($ticket): ?>
<h2><?= $block->escapeHtml(__('Ticket')) ?></h2>
<div class="table-wrapper">
    <table class="data table" id="my-tickets-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('Ticket')) ?></caption>
        <tbody>
            <tr>
                <td class="col"><span class="legend"><?= $block->escapeHtml(__('Subject:')) ?></span> <?= $block->escapeHtml($ticket->getSubject()) ?> </td>
            </tr>
            <tr>
                <td class="col"><span class="legend"><?= $block->escapeHtml(__('Created at:')) ?></span> <?= $block->escapeHtml($block->formatDate($ticket->getCreatedAt(),3,true)) ?></td>
            </tr>
            <tr>
                <td class="col"><span class="legend"> <?= $block->escapeHtml(__('Message:')) ?></span> <?= $block->escapeHtml($ticket->getMessage()) ?></td>
            </tr>
        </tbody>
    </table>
</div>
<?php endif ?>
<?php if ($ticketReplyList && count($ticketReplyList)>0):
    foreach(array_reverse($ticketReplyList) as $ticketReply): ?>
        <fieldset>
            <?php if($ticketReply->getAdmin()!=true&&$block->getSenderName($ticket->getCustomerId())):?>
                <strong> <?= $block->escapeHtml($block->getSenderName($ticket->getCustomerId())) ?> </strong>
            <?php else: ?>
                <strong> <?= $block->escapeHtml('Admin') ?></strong>
            <?php endif ?>
            <div> <?= $block->escapeHtml($ticketReply->getContent()) ?> </div>
            <div> <?= $block->escapeHtml($block->formatDate($ticketReply->getCreatedAt(),3,true)) ?> </div>
        </fieldset>
<?php endforeach; ?>
 <?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
<?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have no ticket replies.')) ?></span></div>
<?php endif;
if($ticket->getOpened()!=false): ?>
<form action="<?= $block->escapeUrl($block->getAddTicketReplyUrl()) ?>) ?>"
      method="post"
      id="form-reply"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <input type="hidden" id="ticket_id" name="ticket_id" value="<?= $ticket->getId() ?>" />
    <fieldset>
        <div class="field required">
            <label for="content" class="label">
                <span><?= $block->escapeHtml(__('Reply')) ?></span>
            </label>
            <div class="control">
                <textarea id="content" name="content" class="input-text" data-validate="{required:true, maxlength: 64000}"></textarea>
            </div>
        </div>
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Reply')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Reply')) ?></span></button>
        </div>
    </fieldset>
</form>
<?php endif ?>
<div class="secondary">
    <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
</div>